// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TableAssociationInitParameters struct {
	GatewayID *string `json:"gatewayId,omitempty" tf:"gateway_id,omitempty"`

	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

type TableAssociationObservation struct {
	GatewayID *string `json:"gatewayId,omitempty" tf:"gateway_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

type TableAssociationParameters struct {

	// +kubebuilder:validation:Optional
	GatewayID *string `json:"gatewayId,omitempty" tf:"gateway_id,omitempty"`

	// +kubebuilder:validation:Optional
	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

// TableAssociationSpec defines the desired state of TableAssociation
type TableAssociationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TableAssociationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TableAssociationInitParameters `json:"initProvider,omitempty"`
}

// TableAssociationStatus defines the observed state of TableAssociation.
type TableAssociationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TableAssociationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TableAssociation is the Schema for the TableAssociations API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,crossplane-k2cloud}
type TableAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.routeTableId) || (has(self.initProvider) && has(self.initProvider.routeTableId))",message="spec.forProvider.routeTableId is a required parameter"
	Spec   TableAssociationSpec   `json:"spec"`
	Status TableAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TableAssociationList contains a list of TableAssociations
type TableAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TableAssociation `json:"items"`
}

// Repository type metadata.
var (
	TableAssociation_Kind             = "TableAssociation"
	TableAssociation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TableAssociation_Kind}.String()
	TableAssociation_KindAPIVersion   = TableAssociation_Kind + "." + CRDGroupVersion.String()
	TableAssociation_GroupVersionKind = CRDGroupVersion.WithKind(TableAssociation_Kind)
)

func init() {
	SchemeBuilder.Register(&TableAssociation{}, &TableAssociationList{})
}
