name: C2Devel/rockitcloud
resources:
    rockitcloud_instance Resource:
        subCategory: ""
        description: 'Creates a compute instance in rockitcloudpage_title: rockitcloud_instance Resource'
        name: rockitcloud_instance Resource
        title: rockitcloud_instance Resource
        argumentDocs:
            <version>_<os>_<arch>.json: |-
                -> providers/c2devel/rockitcloud/<version>/download/<os>/<arch>/index.json
                Важно! Файлы должны быть загружены с mime-типом "application/json". Для файлов должен быть
                открыт доступ на чтение без аутентификации.
            PROVIDER_NAME: '- имя провайдера, по умолчанию: "c2devel/rockitcloud"'
            S3_BACKUP_DIR: |-
                - директория для бэкапа бакета, опционально. Если директория не указана,
                бэкап сделан не будет
            S3_BUCKET: '- имя бакета, по умолчанию: "hc-releases"'
            S3_BUCKET_NAME: '- имя бакета, обязательно'
            S3_REGISTRY_URL: '- url s3 registry, обязательно'
            TF_REGISTRY_URL: '- url terraform registry, по умолчанию: "https://registry.terraform.io/"'
            dist/terraform-provider-rockitcloud_{VERSION}_{OS}_{ARCH}.zip: ""
            docs/: '- инструкции для разработки, roadmap;'
            make testacc: . Сейчас запуск приведет к ошибке, тк большинство тестов еще не адаптировано для запуска вне AWS.
            terraform-provider-rockitcloud_{VERSION}_manifest.json: ""
            version.json: -> providers/c2devel/rockitcloud/versions/index.json
            website/: |-
                - документация к провайдеру, которая публикуется в официальном terraform registry
                (инструкция по документированию от Terraform).
        importStatements: []
