// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AMI) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EIP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Instance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LB) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Route) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Subnet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VPC) Hub() {}
