// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GatewayRoutePropagationInitParameters struct {
	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	VPNGatewayID *string `json:"vpnGatewayId,omitempty" tf:"vpn_gateway_id,omitempty"`
}

type GatewayRoutePropagationObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	VPNGatewayID *string `json:"vpnGatewayId,omitempty" tf:"vpn_gateway_id,omitempty"`
}

type GatewayRoutePropagationParameters struct {

	// +kubebuilder:validation:Optional
	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	// +kubebuilder:validation:Optional
	VPNGatewayID *string `json:"vpnGatewayId,omitempty" tf:"vpn_gateway_id,omitempty"`
}

// GatewayRoutePropagationSpec defines the desired state of GatewayRoutePropagation
type GatewayRoutePropagationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GatewayRoutePropagationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GatewayRoutePropagationInitParameters `json:"initProvider,omitempty"`
}

// GatewayRoutePropagationStatus defines the observed state of GatewayRoutePropagation.
type GatewayRoutePropagationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GatewayRoutePropagationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GatewayRoutePropagation is the Schema for the GatewayRoutePropagations API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,crossplane-k2cloud}
type GatewayRoutePropagation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.routeTableId) || (has(self.initProvider) && has(self.initProvider.routeTableId))",message="spec.forProvider.routeTableId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vpnGatewayId) || (has(self.initProvider) && has(self.initProvider.vpnGatewayId))",message="spec.forProvider.vpnGatewayId is a required parameter"
	Spec   GatewayRoutePropagationSpec   `json:"spec"`
	Status GatewayRoutePropagationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GatewayRoutePropagationList contains a list of GatewayRoutePropagations
type GatewayRoutePropagationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayRoutePropagation `json:"items"`
}

// Repository type metadata.
var (
	GatewayRoutePropagation_Kind             = "GatewayRoutePropagation"
	GatewayRoutePropagation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GatewayRoutePropagation_Kind}.String()
	GatewayRoutePropagation_KindAPIVersion   = GatewayRoutePropagation_Kind + "." + CRDGroupVersion.String()
	GatewayRoutePropagation_GroupVersionKind = CRDGroupVersion.WithKind(GatewayRoutePropagation_Kind)
)

func init() {
	SchemeBuilder.Register(&GatewayRoutePropagation{}, &GatewayRoutePropagationList{})
}
